#define T_BORDER      "┏━━━┯━━━┯━━━┳━━━┯━━━┯━━━┳━━━┯━━━┯━━━┓"
#define B_BORDER      "┗━━━┷━━━┷━━━┻━━━┷━━━┷━━━┻━━━┷━━━┷━━━┛"
#define THICK_CROSS   "╋"
#define THIN_CROSS    "┼"
#define MIXED_CROSS_H "┿"
#define MIXED_CROSS_V "╂"
#define THICK_V_BAR   "┃"
#define THIN_V_BAR    "│"
#define THICK_H_BAR   "━"
#define THIN_H_BAR    "─"
#define CELL_PAD      " "